---
openapi: 3.0.1
info:
  title: Vehicle API V1
  version: v1
  description: This is the first version of my API
components:
  schemas:
    errors_object:
      type: object
      properties:
        errors:
          "$ref": "#/components/schemas/errors_map"
    errors_map:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    vehicles:
      type: array
      additionalProperties:
        type: array
        items:
          "$ref": "#/components/schemas/vehicle"
    vehicle:
      type: object
      properties:
        id:
          type: integer
          example: 1
        license_plate:
          type: string
          example: AAA9999
        make:
          type: string
          example: Mercedes-Benz
        model:
          type: string
          example: '1113'
        color:
          type: string
          example: Azul
        category:
          type: string
          example: Caminhão
        vin:
          type: string
          example: 3TW HZXRAU W3 AA2893
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - license_plate
      - make
      - model
      - color
      - category
      - vin
    vehicle_new:
      type: object
      properties:
        license_plate:
          type: string
          example: ABC9999
        make:
          type: string
          example: Mercedes-Benz
        model:
          type: string
          example: '1113'
        color:
          type: string
          example: Azul
        category:
          type: string
          example: Caminhão
        vin:
          type: string
          example: 3TW HZXRAU W3 AA2893
      required:
      - license_plate
      - make
      - model
      - color
      - category
      - vin
    vehicle_edit:
      type: object
      properties:
        license_plate:
          type: string
          example: AAA9999
        make:
          type: string
          example: Mercedes-Benz
        model:
          type: string
          example: '1113'
        color:
          type: string
          example: Azul
        category:
          type: string
          example: Caminhão
        vin:
          type: 3TW HZXRAU W3 AA2893
paths:
  "/vehicles":
    get:
      summary: list vehicles
      tags:
      - Vehicles
      description: List all vehicles
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
              - id: 570
                license_plate: KUA-5671
                make: BMW
                model: A4
                color: Beige
                category: SUV
                vin: 3CHWCL5AKZY310754
                created_at: '2021-05-21T20:45:55.627Z'
                updated_at: '2021-05-21T20:45:55.627Z'
              - id: 571
                license_plate: NQS1H27
                make: Chevy
                model: A4
                color: Beige
                category: Hatchback
                vin: D1HKD9IW410P55188
                created_at: '2021-05-21T20:45:55.639Z'
                updated_at: '2021-05-21T20:45:55.639Z'
              - id: 572
                license_plate: VTS13V3
                make: Toyota
                model: S5
                color: Orange
                category: Minivan
                vin: OZ7BT54JYE0H75719
                created_at: '2021-05-21T20:45:55.649Z'
                updated_at: '2021-05-21T20:45:55.649Z'
    post:
      summary: create vehicle
      tags:
      - Vehicles
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              example:
                id: 573
                license_plate: BEU2G76
                make: BMW
                model: MKS
                color: Orange
                category: Minivan
                vin: 5D2UJY9A060G80428
                created_at: '2021-05-21T20:45:55.737Z'
                updated_at: '2021-05-21T20:45:55.737Z'
        '422':
          description: unprocessable_entity
          content:
            application/json:
              example:
                errors:
                  license_plate:
                  - can't be blank
                  make:
                  - can't be blank
                  model:
                  - can't be blank
                  color:
                  - can't be blank
                  category:
                  - can't be blank
                  vin:
                  - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/vehicle_new"
  "/vehicles/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: show vehicle
      tags:
      - Vehicles
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                id: 574
                license_plate: GOC5R77
                make: Ford
                model: MKZ
                color: Beige
                category: SUV
                vin: INB0IZD0780074597
                created_at: '2021-05-21T20:45:55.790Z'
                updated_at: '2021-05-21T20:45:55.790Z'
        '404':
          description: not_found
          content:
            application/json:
              example:
                message: Record not found
    patch:
      summary: update vehicle
      tags:
      - Vehicles
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                license_plate: HHF2C80
                model: Altima
                make: Buick
                color: Grey
                category: Regular Cab Pickup
                vin: 651K1OAM6FLQ80816
                id: 575
                created_at: '2021-05-21T20:45:55.866Z'
                updated_at: '2021-05-21T20:45:55.890Z'
        '404':
          description: not_found
          content:
            application/json:
              example:
                message: Record not found
        '422':
          description: unprocessable_entity
          content:
            application/json:
              example:
                errors:
                  license_plate:
                  - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/vehicle_edit"
    put:
      summary: update vehicle
      tags:
      - Vehicles
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                license_plate: JAE6J53
                model: Malibu
                make: Dodge
                color: Red
                category: Hatchback
                vin: U3KNA8EY8G0N73741
                id: 577
                created_at: '2021-05-21T20:45:55.979Z'
                updated_at: '2021-05-21T20:45:55.999Z'
        '404':
          description: not_found
          content:
            application/json:
              example:
                message: Record not found
        '422':
          description: unprocessable_entity
          content:
            application/json:
              example:
                errors:
                  license_plate:
                  - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/vehicle_edit"
    delete:
      summary: delete vehicle
      tags:
      - Vehicles
      responses:
        '204':
          description: no_content
        '404':
          description: not_found
          content:
            application/json:
              example:
                message: Record not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
